export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';


// action types for singup
export const SET_SIGNUP_DETAILS = "SET_SIGNUP_DETAILS";
export const TOGGLE_SIGNUP_LOADER = "TOGGLE_SIGNUP_LOADER";
export const SET_SIGNUP_ERROR_MESSAGE = "SET_SIGNUP_ERROR_MESSAGE";
export const RESET_SIGNUP_STATE = "RESET_SIGNUP_STATE"